version: '3.9'

services:
  db:
    image: postgres:15
    container_name: investment_postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: project
      POSTGRES_PASSWORD: bdFGMaZvmH5VTWn@
      POSTGRES_DB: investment_db
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: investment_app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma migrate deploy &&
        npx prisma db seed &&
        npm run start:dev
      "

volumes:
  pg_data:
